//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apeam1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sales()
        {
            this.sale_details = new HashSet<sale_details>();
        }
    
        public int Id { get; set; }
        public string customer { get; set; }
        public System.DateTime date_sale { get; set; }
        public string payment { get; set; }
        public Nullable<double> total_sale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_details> sale_details { get; set; }
    }
}
